function $(b){return document.getElementById(b)}function addLoadEvent(b){var a=window.onload;window.onload="function"!=typeof window.onload?b:function(){a();b()}}function insertAfter(b,a){var c=a.parentNode;c.lastChild==a?c.appendChild(b):c.insertBefore(b,a.nextSibling)}function addClass(b,a){b.className=b.className?b.className+(" "+a):a}
function highlightPage(){if(!document.getElementsByTagName)return!1;var b=window.location.href,a=document.getElementsByTagName("header");if(0==a.length)return!1;a=a[0].getElementsByTagName("nav");if(0==a.length)return!1;for(var a=a[0].getElementsByTagName("a"),c=0;c<a.length;c++){var e=a[c].getAttribute("href");if(-1!=b.indexOf(e)){addClass(a[c],"here");var d=a[c].firstChild.nodeValue.toLowerCase()}document.getElementsByTagName("body")[0].setAttribute("id",d)}}
function prepareSlides(){if(!(document.createElement&&document.createTextNode&&document.getElementById&&document.getElementById("intro")))return!1;var b=$("intro"),a=document.createElement("div");a.setAttribute("id","placeholderArea");insertAfter(a,b);b=document.createElement("img");b.setAttribute("id","placeholder");b.setAttribute("src","images/pet.png");b.setAttribute("alt","Boxes");a.appendChild(b)}
function move(b,a,c,e){if(!document.getElementById||!document.getElementById(b))return!1;var d=$(b);d.movement&&clearTimeout(d.movement);d.style.left||(d.style.left="0px");d.style.top||(d.style.top="0px");var f=parseFloat(d.style.left),g=parseFloat(d.style.top);if(f==a&&g==c)return!0;d.style.left=f+(a-f)/10+"px";d.style.top=g+(c-g)/10+"px";d.movement=setTimeout("move('"+b+"',"+a+","+c+","+e+")",e)}
function prepareMove(){if(!document.getElementsByTagName||!document.getElementById||!document.getElementById("placeholder"))return!1;$("placeholder");var b=document.getElementsByTagName("a"),a;if(0==b.length)return!1;for(var c=0;c<b.length;c++)b[c].onmouseover=function(){a=this.getAttribute("href");-1!=a.indexOf("home")&&move("placeholder",0,0,5);-1!=a.indexOf("about")&&move("placeholder",-300,0,5);-1!=a.indexOf("photos")&&move("placeholder",-600,0,5);-1!=a.indexOf("live")&&move("placeholder",-900,
0,5);-1!=a.indexOf("contact")&&move("placeholder",-1200,0,5)}}
function prepareSection(){if(!document.getElementById||!document.getElementsByTagName||!document.getElementsByTagName("article"))return!1;var b=document.getElementsByTagName("article");if(0==b.length)return!1;b=b[0].getElementsByTagName("nav");if(0==b.length)return!1;for(var b=b[0].getElementsByTagName("a"),a=0;a<b.length;a++){var c=b[a].getAttribute("href").split("#")[1];document.getElementById(c)&&(document.getElementById(c).style.display="none",b[a].des=c,b[a].onclick=function(){showSection(this.des);
return!1})}}function showSection(b){for(var a=document.getElementsByTagName("section"),c=0;c<a.length;c++)a[c].getAttribute("id")!=b?a[c].style.display="none":a[c].style.display="block"}function prepareGralley(){if(!document.getElementsByTagName||!document.getElementById||!document.getElementById("gallery"))return!1;for(var b=$("gallery").getElementsByTagName("a"),a=0;a<b.length;a++)b[a].onclick=function(){return showPic(this)}}
function prepareImage(){if(!(document.createElement&&document.createTextNode&&document.getElementById&&document.getElementById("gallery")))return!1;var b=$("gallery"),a=document.createElement("img");a.setAttribute("id","imgPlaceholder");a.setAttribute("src","images/photos/0.jpg");a.setAttribute("alt","Pet");insertAfter(a,b);var b=document.createTextNode("Cat"),c=document.createElement("p");c.setAttribute("id","description");c.appendChild(b);a.parentNode.insertBefore(c,a)}
function showPic(b){if(!document.getElementById("imgPlaceholder"))return!1;var a=$("imgPlaceholder"),c=b.getAttribute("href");a.setAttribute("src",c);if(!document.getElementById("description"))return!1;a=$("description");b=b.getAttribute("title")?b.getAttribute("title"):"";3==a.firstChild.nodeType&&(a.firstChild.nodeValue=b);return!1}
function stripeTables(){if(!document.getElementsByTagName)return!1;for(var b=document.getElementsByTagName("table"),a,c,e=0;e<b.length;e++){a=!1;c=b[e].getElementsByTagName("tr");for(var d=0;d<c.length;d++)1==a?(addClass(c[d],"odd"),a=!1):(addClass(c[d],"eve"),a=!0)}}
function prepareHighlight(){if(!document.getElementsByTagName)return!1;for(var b=document.getElementsByTagName("tr"),a=0;a<b.length;a++)b[a].oldClass=b[a].className,b[a].onmouseover=function(){addClass(this,"highlight")},b[a].onmouseout=function(){this.className=this.oldClass}}function prepareAbbr(){var b=document.getElementsByTagName("article")[0];displayAbbr(b)}
function displayAbbr(b){if(!document.getElementsByTagName||!document.createElement||!document.createTextNode)return!1;var a=document.getElementsByTagName("abbr");if(1>a.length)return!1;for(var c=[],e=0;e<a.length;e++)if(!(1>a[e].childNodes.length)){var d=a[e].firstChild.nodeValue;c[d]=a[e].getAttribute("title")}a=document.createElement("dl");for(d in c){var e=document.createElement("dt"),f=document.createTextNode(d);e.appendChild(f);a.appendChild(e);e=document.createElement("dd");f=document.createTextNode(c[d]);
e.appendChild(f);a.appendChild(e)}if(1>a.childNodes.length)return!1;c=document.createElement("h1");d=document.createTextNode("abbreviations");c.appendChild(d);b.appendChild(c);b.appendChild(a)}
function focusLabels(){if(!document.getElementsByTagName||!document.getElementById)return!1;for(var b=document.getElementsByTagName("label"),a=0;a<b.length;a++)b[a].getAttribute("for")&&(b[a].onclick=function(){var a=this.getAttribute("for");if(!document.getElementById(a))return!1;document.getElementById(a).focus()})}
function resetFields(b){if(!Modernizr.input.placeholder){if(!document.getElementsByTagName)return!1;b=b.elements;for(var a=0;a<b.length;a++){var c=b[a];"submit"!=c.type&&"reset"!=c.type&&(c.placeholder||c.getAttribute("placeholder"))&&(c.onfocus=function(){var a=c.placeholder||c.getAttribute("placeholder");this.value==a&&(this.className=this.value="")},c.onblur=function(){""==this.value&&(this.value=this.placeholder||this.getAttribute("placeholder"),addClass(this,"holder"))})}}}
function isText(b){if(0==b.value.replace(" ","").length)return!1;var a=b.placeholder||b.getAttribute("placeholder");return b.value!=a}function isEmail(b){return-1!=b.value.indexOf("@")&&-1!=b.value.indexOf(".")}function validateForm(b){b=b.elements;for(var a=0;a<b.length;a++){var c=b[a];if("required"==c.required&&!isText(c))return alert("Please fill in the "+c.name+"field."),!1;if("email"==c.type&&!isEmail(c))return alert("The "+c.name+"field must be a valid email address."),!1}return!0}
function submitFormWithAjax(b,a){var c=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHttp");if(!c)return!1;displayLoading(a);for(var e=[],d,f=0;f<b.elements.length;f++)d=b.elements[f],e[f]=d.name+"="+encodeURIComponent(d.value);e=e.join("&");c.open("POST",b.getAttribute("action"),!0);c.setRequestHeader("Content-type","application/x-www-form-urlencoded");c.onreadystatechange=function(){if(4==c.readyState)if(200==c.status||0==c.status){var b=c.responseText.match(/<article>([\s\S]+)<\/article>/);
a.innerHTML=0<b.length?b[1]:"<p>error!</p>"}else a.innerHTML="<p>"+c.statusText+"</p>"};c.send(e);return!0}function displayLoading(b){for(;b.hasChildNodes();)b.removeChild(b.lastChild);var a=document.createElement("img");a.setAttribute("src","images/loading.gif");a.setAttribute("alt","loading...");b.appendChild(a)}
function prepareForms(){for(var b=document.getElementsByTagName("form"),a=0;a<b.length;a++){var c=b[a];resetFields(c);c.onsubmit=function(){if(!validateForm(c))return!1;var a=document.getElementsByTagName("article")[0];return submitFormWithAjax(c,a)?!1:!0}}}addLoadEvent(prepareImage);addLoadEvent(prepareGralley);addLoadEvent(prepareSlides);addLoadEvent(prepareMove);addLoadEvent(highlightPage);addLoadEvent(prepareSection);addLoadEvent(stripeTables);addLoadEvent(prepareAbbr);addLoadEvent(prepareHighlight);
addLoadEvent(focusLabels);addLoadEvent(prepareForms);